POST http://localhost:3002/user/login
Content-Type: application/json

{
  "username": "Alexer000",
  "password": "Alexer000"
}

###
POST http://localhost:3002/user/register
Content-Type: application/json

{
  "username": "Alexer000",
  "name": "Alex",
  "password": "Alexer000"
}

### 
POST http://localhost:3002/menu/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhlcjAwMCIsImlkIjoiNjEyYWUxM2E4MzZhMmYyMjE4NjA1M2UyIiwiaWF0IjoxNjMwMjA4ODg5fQ.edvf-OX-O5B7eu_eM6ZeZiDTkV-aivoVq1VOERxuJKY

{
  "name": "Ice cream sandwich2",
  "price": 4.5,
  "category": "dessert"
}

### 
DELETE  http://localhost:3002/menu/products/612b04ea877b6d1d8c502e4b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhlcjAwMCIsImlkIjoiNjEyYWUxM2E4MzZhMmYyMjE4NjA1M2UyIiwiaWF0IjoxNjMwMjA4ODg5fQ.edvf-OX-O5B7eu_eM6ZeZiDTkV-aivoVq1VOERxuJKY

{
  "id": "612b04ea877b6d1d8c502e4b"
}

###
POST http://localhost:3002/cart
Content-Type: application/json

{
  "productId": "6129abc24c9e6253f8475a0e",
  "quantity": 3
}

###
POST http://localhost:3002/cart
Content-Type: application/json

{
  "productId": "6129abcd4c9e6253f8475a12",
  "quantity": 3
}

###
POST http://localhost:3002/cart/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhlcjAwMCIsImlkIjoiNjEyYWUxM2E4MzZhMmYyMjE4NjA1M2UyIiwiaWF0IjoxNjMwMjA4ODg5fQ.edvf-OX-O5B7eu_eM6ZeZiDTkV-aivoVq1VOERxuJKY

{
  "subTotal": 17.5,
  "items": [
    {
      "productId": "6129abcd4c9e6253f8475a12",
      "name": "Orange Soda",
      "quantity": 3,
      "price": 3.5,
      "total": 10.5
    },
    {
      "productId": "6129abc24c9e6253f8475a0e",
      "name": "Coke",
      "quantity": 3,
      "price": 3.5,
      "total": 7
    }
  ]
}